### ISSUE TITLE
some problem happend

### ISSUE THREAD

**Issue by bage2017** [gabrielchaves7/flutterImageEditor#1]
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
W/art     ( 4890): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[14,tid=4907,Native,Thread*=0xa007e800,peer=0x12d510a0,"Thread-159"]
D/        ( 4890): HostConnection::get() New Host Connection established 0xad829350, tid 4934
D/        ( 4890): HostConnection::get() New Host Connection established 0xb3f237d0, tid 4933
I/Choreographer( 4890): Skipped 60 frames!  The application may be doing too much work on its main thread.
I/flutter ( 4890): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4890): The following FileSystemException was thrown attaching to the render tree:
I/flutter ( 4890): Cannot open file, path =
I/flutter ( 4890): '/storage/emulated/0/Android/data/com.example.editor_foto_example/files/naruto.jpg' (OS Error: No
I/flutter ( 4890): such file or directory, errno = 2)
I/flutter ( 4890): When the exception was thrown, this was the stack:
I/flutter ( 4890): #0      _File.throwIfError (dart:io/file_impl.dart:643:7)
I/flutter ( 4890): #1      _File.openSync (dart:io/file_impl.dart:487:5)
I/flutter ( 4890): #2      _File.readAsBytesSync (dart:io/file_impl.dart:547:18)
I/flutter ( 4890): #3      _WidgetEditableImage.initState (package:editor_foto_example/main.dart:42:37)
I/flutter ( 4890): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
I/flutter ( 4890): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 4890): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 4890): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 4890): #8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:939:16)
I/flutter ( 4890): #9      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:910:5)
I/flutter ( 4890): #10     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:856:17)
I/flutter ( 4890): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
I/flutter ( 4890): #12     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:855:13)
I/flutter ( 4890): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
I/flutter ( 4890): #14     runApp (package:flutter/src/widgets/binding.dart:786:7)
I/flutter ( 4890): #15     main (package:editor_foto_example/main.dart:13:3)
I/flutter ( 4890): #26     getExternalStorageDirectory (package:path_provider/path_provider.dart)
I/flutter ( 4890): #37     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
I/flutter ( 4890): (elided 34 frames from package dart:async and package dart:async-patch)
I/flutter ( 4890): ════════════════════════════════════════════════════════════════════════════════════════════════════

could you help me?
I first study flutter,can't solve this problem

**Comment by gabrielchaves7** [comment]
Sorry man, i only see this now. I will fix that and update. If you need more help you can text me on my email: gabrielbum@gmail.com.

**Comment by bage2017** [comment]
thank you very much。i search other solution to solve the tools。if i have solution，we study together




| |
何勇
邮箱：hxiaoxuey@163.com
|

签名由 网易邮箱大师 定制

On 09/11/2019 21:05, Gabriel Chaves wrote:

Sorry man, i only see this now. I will fix that and update. If you need more help you can text me on my email: gabrielbum@gmail.com.

**Comment by gabrielchaves7** [comment]
I fix the problem, if you want to give another try to the plugin i will appreciate. Any doubts just ask :)

**Comment by bage2017** [comment]
thank you。i will run the newest code.




| |
何勇
邮箱：hxiaoxuey@163.com
|

签名由 网易邮箱大师 定制

On 09/16/2019 07:00, Gabriel Chaves wrote:

I fix the problem, if you want to give another try to the plugin i will appreciate. Any doubts just ask :)
