### ISSUE TITLE
it takes much time to process on large images

### ISSUE THREAD

**Issue by SanketKachhela** [gabrielchaves7/flutterImageEditor#3]
hi this is working fine for small images but hangs on large images, any solution for this  ?

**Comment by gabrielchaves7** [comment]
I talk about it on readme, you should always try to send compress images, and after edit the image you can decompress and work normally with it. You can use a package for it, like flutter_image_compress . Sorry for take too long to answer, if you need a example of it or if i can help you with anything else just say o/

**Comment by gabrielchaves7** [comment]
@SanketKachhela closing.
